CREATE TABLE `vacina`.`pessoa` (
  `IDPESSOA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `DATANASCIMENTO` DATE NOT NULL,
  `SEXO` VARCHAR(2) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `TIPOPESSOA` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDVACINA`),
  UNIQUE INDEX `ID_UNIQUE` (`IDVACINA` ASC) VISIBLE);
  
  
  CREATE TABLE `vacina`.`vacina` (
  `IDPESSOA` INT NOT NULL AUTO_INCREMENT,
  `NOMEVACINA` VARCHAR(3) NOT NULL,
  `PAISORIGEM` VARCHAR(9) NOT NULL,
  `DATAINICIOPESQUISA` DATE NOT NULL,
  `PESQUISADORRESPONSAVEL` VARCHAR(255) NOT NULL,
  `ESTAGIO` VARCHAR(3) INT NULL,
  PRIMARY KEY (`ID`));